name: Shell Commands


on: [push]

jobs:
  run-shell-Command: 
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "Hello World"
        - name: echo the end of process
          run: echo "Process Ended"  
        - name: multiline script
          run: |
            node -v
            npm -v
            